### ISSUE TITLE
error in after '"npm install modbus'

### ISSUE THREAD

**Issue by bShnaider** [tuxnsk/nodejs_libmodbus#10]
hi,

I am trying to install the module with "npm install modbus" but i get the following errors:
npm ERR! modbus@0.0.13 install: `./make_libmodbus.sh && node-gyp configure --python=python2 && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the modbus@0.0.13 install script.
npm ERR! This is most likely a problem with the modbus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./make_libmodbus.sh && node-gyp configure --python=python2 && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls modbus
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "modbus"
npm ERR! cwd /home/neov/Desktop/test
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/neov/Desktop/test/npm-debug.log
npm ERR! not ok code 0

I would appreciate your help,
thanks.

**Comment by ProteusCortex** [comment]
Closing due to inactivity.

**Comment by amechti** [comment]
I have the same problem please i need help !!
thanx

**Comment by ProteusCortex** [comment]
The original issue or the one @Bzhnja mentioned?

**Comment by lamyra** [comment]
no the original npm install modbus

**Comment by ProteusCortex** [comment]
Can you, please, attach the `npm-error.log` file that npm produces after the error?

**Comment by jannhama** [comment]
nmp install issue here as well. This is the debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'modbus' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of t:\tstmodbus\package.json
5 warn package.json tst-Modbus@1.0.0 No repository field.
6 warn package.json tst-Modbus@1.0.0 No README data
7 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\bower\package.json
8 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\browser-sync\package.json
9 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\express\package.json
10 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp\package.json
11 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp-concat\package.json
12 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp-ignore\package.json
13 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp-jshint\package.json
14 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp-load-plugins\package.json
15 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp-sass\package.json
16 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp-uglify\package.json
17 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\gulp-util\package.json
18 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\jshint-stylish\package.json
19 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\jsmodbus\package.json
20 verbose installManyTop reading scoped package data from t:\tstmodbus\node_modules\main-bower-files\package.json
21 info package.json browser-sync@1.9.2 No license field.
22 info package.json bower@1.4.1 No license field.
23 info package.json gulp-ignore@1.2.1 No license field.
24 verbose readDependencies loading dependencies from t:\tstmodbus\package.json
25 silly cache add args [ 'modbus', null ]
26 verbose cache add spec modbus
27 silly cache add parsed spec { raw: 'modbus',
27 silly cache add   scope: null,
27 silly cache add   name: 'modbus',
27 silly cache add   rawSpec: '',
27 silly cache add   spec: '*',
27 silly cache add   type: 'range' }
28 silly addNamed modbus@*
29 verbose addNamed "*" is a valid semver range for modbus
30 silly addNameRange { name: 'modbus', range: '*', hasData: false }
31 silly mapToRegistry name modbus
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/modbus
35 verbose addNameRange registry:https://registry.npmjs.org/modbus not in flight; fetching
36 verbose request uri https://registry.npmjs.org/modbus
37 verbose request no auth needed
38 info attempt registry request try #1 at 09:27:21
39 verbose request id 90ca837cda04637f
40 verbose etag "BPUH1MRHSVB6IZQUYQMS5YTPX"
41 http request GET https://registry.npmjs.org/modbus
42 http 304 https://registry.npmjs.org/modbus
43 silly get cb [ 304,
43 silly get   { date: 'Mon, 13 Jul 2015 06:27:21 GMT',
43 silly get     via: '1.1 varnish',
43 silly get     'cache-control': 'max-age=60',
43 silly get     etag: '"BPUH1MRHSVB6IZQUYQMS5YTPX"',
43 silly get     age: '0',
43 silly get     connection: 'keep-alive',
43 silly get     'x-served-by': 'cache-ams4129-AMS',
43 silly get     'x-cache': 'MISS',
43 silly get     'x-cache-hits': '0',
43 silly get     'x-timer': 'S1436768841.461425,VS0,VE438',
43 silly get     vary: 'Accept' } ]
44 verbose etag https://registry.npmjs.org/modbus from cache
45 verbose get saving modbus to C:\Users\janne.hamalainen\AppData\Roaming\npm-cache\registry.npmjs.org\modbus\.cache.json
46 silly addNameRange number 2 { name: 'modbus', range: '*', hasData: true }
47 silly addNameRange versions [ 'modbus',
47 silly addNameRange   [ '0.0.1',
47 silly addNameRange     '0.0.2',
47 silly addNameRange     '0.0.3',
47 silly addNameRange     '0.0.4',
47 silly addNameRange     '0.0.5',
47 silly addNameRange     '0.0.6',
47 silly addNameRange     '0.0.7',
47 silly addNameRange     '0.0.8',
47 silly addNameRange     '0.0.9',
47 silly addNameRange     '0.0.10',
47 silly addNameRange     '0.0.11',
47 silly addNameRange     '0.0.12',
47 silly addNameRange     '0.0.13' ] ]
48 silly addNamed modbus@0.0.13
49 verbose addNamed "0.0.13" is a plain semver version for modbus
50 silly cache afterAdd modbus@0.0.13
51 verbose afterAdd C:\Users\janne.hamalainen\AppData\Roaming\npm-cache\modbus\0.0.13\package\package.json not in flight; writing
52 verbose afterAdd C:\Users\janne.hamalainen\AppData\Roaming\npm-cache\modbus\0.0.13\package\package.json written
53 silly install resolved [ { name: 'modbus',
53 silly install resolved     version: '0.0.13',
53 silly install resolved     description: 'libmodbus binding',
53 silly install resolved     keywords: [ 'modbus' ],
53 silly install resolved     main: 'modbus.js',
53 silly install resolved     engines: { node: '>= 0.8.0' },
53 silly install resolved     scripts:
53 silly install resolved      { install: './make_libmodbus.sh && node-gyp configure --python=python2 && node-gyp build',
53 silly install resolved        preuninstall: 'rm -rf libmodbus build' },
53 silly install resolved     author: { name: 'Davydov Denis', email: 'mail@tuxnsk.ru' },
53 silly install resolved     maintainers: [ [Object] ],
53 silly install resolved     repository:
53 silly install resolved      { type: 'git',
53 silly install resolved        url: 'git+https://github.com/tuxnsk/nodejs_libmodbus.git' },
53 silly install resolved     license: 'BSD',
53 silly install resolved     gitHead: '40574c8876af3a8b56e64b34b2623dbf45b8e811',
53 silly install resolved     bugs: { url: 'https://github.com/tuxnsk/nodejs_libmodbus/issues' },
53 silly install resolved     homepage: 'https://github.com/tuxnsk/nodejs_libmodbus',
53 silly install resolved     _id: 'modbus@0.0.13',
53 silly install resolved     _shasum: '40e76e9557df992bcbf802f8cf7756002fbb40c7',
53 silly install resolved     _from: 'modbus@*',
53 silly install resolved     _npmVersion: '2.0.2',
53 silly install resolved     _nodeVersion: '0.10.32',
53 silly install resolved     _npmUser: { name: 'tuxnsk', email: 'mail@tuxnsk.ru' },
53 silly install resolved     dist:
53 silly install resolved      { shasum: '40e76e9557df992bcbf802f8cf7756002fbb40c7',
53 silly install resolved        tarball: 'http://registry.npmjs.org/modbus/-/modbus-0.0.13.tgz' },
53 silly install resolved     directories: {},
53 silly install resolved     _resolved: 'https://registry.npmjs.org/modbus/-/modbus-0.0.13.tgz',
53 silly install resolved     readme: 'ERROR: No README data found!' } ]
54 info install modbus@0.0.13 into t:\tstmodbus
55 info installOne modbus@0.0.13
56 verbose installOne of modbus to t:\tstmodbus not in flight; installing
57 verbose lock using C:\Users\janne.hamalainen\AppData\Roaming\npm-cache\_locks\modbus-cc6b521a7907d9d9.lock for t:\tstmodbus\node_modules\modbus
58 silly install write writing modbus 0.0.13 to t:\tstmodbus\node_modules\modbus
59 verbose unbuild node_modules\modbus
60 silly gentlyRm t:\tstmodbus\node_modules\modbus is being purged from base t:\tstmodbus
61 verbose gentlyRm don't care about contents; nuking t:\tstmodbus\node_modules\modbus
62 verbose tar unpack C:\Users\janne.hamalainen\AppData\Roaming\npm-cache\modbus\0.0.13\package.tgz
63 verbose tar unpacking to t:\tstmodbus\node_modules\modbus
64 silly gentlyRm t:\tstmodbus\node_modules\modbus is being purged
65 verbose gentlyRm don't care about contents; nuking t:\tstmodbus\node_modules\modbus
66 silly gunzTarPerm modes [ '777', '666' ]
67 silly gunzTarPerm extractEntry package.json
68 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
69 silly gunzTarPerm extractEntry README.md
70 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
71 silly gunzTarPerm extractEntry modbus.js
72 silly gunzTarPerm modified mode [ 'modbus.js', 420, 438 ]
73 silly gunzTarPerm extractEntry binding.gyp
74 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
75 silly gunzTarPerm extractEntry configure.patch
76 silly gunzTarPerm modified mode [ 'configure.patch', 420, 438 ]
77 silly gunzTarPerm extractEntry examples/master.js
78 silly gunzTarPerm modified mode [ 'examples/master.js', 420, 438 ]
79 silly gunzTarPerm extractEntry examples/master_native.js
80 silly gunzTarPerm modified mode [ 'examples/master_native.js', 420, 438 ]
81 silly gunzTarPerm extractEntry examples/slave.js
82 silly gunzTarPerm modified mode [ 'examples/slave.js', 420, 438 ]
83 silly gunzTarPerm extractEntry make_libmodbus.sh
84 silly gunzTarPerm modified mode [ 'make_libmodbus.sh', 493, 511 ]
85 silly gunzTarPerm extractEntry mt.patch
86 silly gunzTarPerm modified mode [ 'mt.patch', 420, 438 ]
87 silly gunzTarPerm extractEntry src/main.cpp
88 silly gunzTarPerm modified mode [ 'src/main.cpp', 420, 438 ]
89 silly gunzTarPerm extractEntry wscript
90 silly gunzTarPerm modified mode [ 'wscript', 420, 438 ]
91 verbose write writing to t:\tstmodbus\node_modules\modbus\package.json
92 info preinstall modbus@0.0.13
93 verbose readDependencies loading dependencies from t:\tstmodbus\node_modules\modbus\package.json
94 verbose readDependencies loading dependencies from t:\tstmodbus\node_modules\modbus\package.json
95 silly install resolved []
96 verbose about to build t:\tstmodbus\node_modules\modbus
97 info build t:\tstmodbus\node_modules\modbus
98 info linkStuff modbus@0.0.13
99 silly linkStuff modbus@0.0.13 has t:\tstmodbus\node_modules as its parent node_modules
100 verbose linkBins modbus@0.0.13
101 verbose linkMans modbus@0.0.13
102 verbose rebuildBundles modbus@0.0.13
103 info install modbus@0.0.13
104 verbose unsafe-perm in lifecycle true
105 info modbus@0.0.13 Failed to exec install script
106 verbose unlock done using C:\Users\janne.hamalainen\AppData\Roaming\npm-cache\_locks\modbus-cc6b521a7907d9d9.lock for t:\tstmodbus\node_modules\modbus
107 verbose stack Error: modbus@0.0.13 install: `./make_libmodbus.sh && node-gyp configure --python=python2 && node-gyp build`
107 verbose stack Exit status 1
107 verbose stack     at EventEmitter.<anonymous> (c:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
107 verbose stack     at EventEmitter.emit (events.js:110:17)
107 verbose stack     at ChildProcess.<anonymous> (c:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
107 verbose stack     at ChildProcess.emit (events.js:110:17)
107 verbose stack     at maybeClose (child_process.js:1015:16)
107 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
108 verbose pkgid modbus@0.0.13
109 verbose cwd t:\tstmodbus
110 error Windows_NT 6.3.9600
111 error argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "modbus"
112 error node v0.12.5
113 error npm  v2.11.2
114 error code ELIFECYCLE
115 error modbus@0.0.13 install: `./make_libmodbus.sh && node-gyp configure --python=python2 && node-gyp build`
115 error Exit status 1
116 error Failed at the modbus@0.0.13 install script './make_libmodbus.sh && node-gyp configure --python=python2 && node-gyp build'.
116 error This is most likely a problem with the modbus package,
116 error not with npm itself.
116 error Tell the author that this fails on your system:
116 error     ./make_libmodbus.sh && node-gyp configure --python=python2 && node-gyp build
116 error You can get their info via:
116 error     npm owner ls modbus
116 error There is likely additional logging output above.
117 verbose exit [ 1, true ]
118 verbose unbuild node_modules\modbus
119 info preuninstall modbus@0.0.13
120 verbose unsafe-perm in lifecycle true
121 info uninstall modbus@0.0.13
122 verbose unbuild rmStuff modbus@0.0.13 from t:\tstmodbus\node_modules
123 info postuninstall modbus@0.0.13
124 silly gentlyRm t:\tstmodbus\node_modules\modbus is being purged from base t:\tstmodbus
125 verbose gentlyRm don't care about contents; nuking t:\tstmodbus\node_modules\modbus
126 silly vacuum-fs purging t:\tstmodbus\node_modules\modbus
127 silly vacuum-fs quitting because other entries in t:\tstmodbus\node_modules
